services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    environment:
      PROTHEUS_API_KEY: ${PROTHEUS_API_KEY}
      NGINX_ENVSUBST_VARS: '$PROTHEUS_API_KEY'
    container_name: sarem_web
    ports:
      - "82:82"
    restart: unless-stopped
