server {
    listen 82;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Suporte para o React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de arquivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # Desativar acesso a arquivos ocultos
    location ~ /\. {
        deny all;
    }
}
