ALTER TABLE public.bo_records
    ADD COLUMN IF NOT EXISTS custo VARCHAR(50),
    ADD COLUMN IF NOT EXISTS procedencia BOOLEAN,
    ADD COLUMN IF NOT EXISTS causa VARCHAR(100),
    ADD COLUMN IF NOT EXISTS falha TEXT;